development:
  host: '127.0.0.1'
  port: 9042
  keyspace: kenny_loggins_development
  max_retries: 3
  retry_delay: 0.5

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: kenny_loggins_test
  max_retries: 3
  retry_delay: 0.5

